### ISSUE TITLE
npm package of angular2-qrscanner@0.1.6 is broken

### ISSUE THREAD

**Issue by superopengl** [goergch/angular2-qrscanner#12]
`npm install angular2-qrscanner@0.1.6` installs an empty package. There is no any js file nor dist folder under `node_modules/angular2-qrscanner`.
![image](https://cloud.githubusercontent.com/assets/1570516/26663171/5d33c148-46cc-11e7-8e75-ae69fb439f97.png)

As a workaround, I installed it with URL.
`npm install https://github.com/goergch/angular2-qrscanner`

**Comment by moshmage** [comment]
waiting on @goergch to accept the revert and issue the publish command. and yes, this problem was my fault :\

**Comment by goergch** [comment]
V 0.1.7 is published
