### ISSUE TITLE
Importing ?

### ISSUE THREAD

**Issue by spine42** [goergch/angular2-qrscanner#13]
Hey guys,
Can you give pointers regarding how we use the package ?
I suppose we need to import something ...

Thanks ! :-)

**Comment by moshmage** [comment]
check the readme :) https://github.com/goergch/angular2-qrscanner/blob/master/README.md

**Comment by spine42** [comment]
Thanks for your quick reply, I'm new to angular 4+ so I was looking for a way to import into the app module.

The following did the trick :
`import { QrScannerModule } from 'angular2-qrscanner';`
