### ISSUE TITLE
Issue with production builds in angular

### ISSUE THREAD

**Issue by kmkatsma** [goergch/angular2-qrscanner#14]
I'm getting this error below when trying to compile in production mode, using the npm published version (which seems go come from fork?)

ERROR in d:/a/1/s/src/$$_gendir/node_modules/angular2-qrscanner/src/qrscanner.component.ngfactory.ts (62,31): Property 'supported' is private and only accessible within class 'QrScannerComponent'.

I found that I could make this public and get around the issue locally, but if using a build server it's going to need to this property changed in the source.

**Comment by moshmage** [comment]
@kmkatsma What version of Angular are you using? I noticed some changes regarding `ngfactory` files in the last changelog but I haven't had the time to a) look it up nor b) run this on the @latest of angular.

I'll ping you when I find something

**Comment by kmkatsma** [comment]
We're using 4.2.2.   Everything works like a charm, just the production build has issue with visibility of supported property.

To get around we just locally updated qrscanner.component.ts  to change the property "supported" from:

**private** supported = true;

to:

**public** supported = true;
