### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by gonzalo-pantalena** [goergch/angular2-qrscanner#15]
Hi, this is not an issue but I don't know other way to ask questions

 I'm new on Angular 2, maybe it's a stupid question, but I'm trying to import the 'QrScannerComponent' doing:
 
import * as qr from 'angular2-qrscanner\src\qrscanner.component'
OR
import * as qr from 'angular2-qrscanner\dist\src\qrscanner.component'

with both, my code doesn't show errors, but when I test in browser, it says that can't find the 'qrscanner.component.js', so I tried importing from 'angular2-qrscanner\src\qrscanner.component.js' and get another Not found error, that would require to update the library.

I think I'm missing something on the importation, but I can't find any suggestion that works.

I hope that make sense, english is not my native language

Thanks

**Comment by moshmage** [comment]
@gonzalo-pantalena there's an updated version of the readme (that was lacking); Here's what you should do:

```ts
import { QrScannerModule } from 'angular2-qrscanner';
@NgModule({
  declarations: [
    // ...
  ],
  imports: [
    // ...
    QrScannerModule,
  ],
  providers: [],
  bootstrap: [
      
  ]
})
export class AppModule { }
```
