### ISSUE TITLE
Uncaught TypeError: Cannot set property 'gUM' of undefined at errror (qrscanner.component.ts:79)

### ISSUE THREAD

**Issue by perkma** [goergch/angular2-qrscanner#2]
I've just added angular2-qrscanner to my project and when I load my site in chrome I get the following error message in debug console:
Uncaught TypeError: Cannot set property 'gUM' of undefined at errror (qrscanner.component.ts:79)

If I change the line 79 in qrscanner.component.ts (and of course in .js) from
this.gUM=false
to
self.gUM=false
then everything works fine.

**Comment by moshmage** [comment]
closed by #7
