### ISSUE TITLE
Fresh install of component doesn't work

### ISSUE THREAD

**Issue by dewolft** [goergch/angular2-qrscanner#20]
I try the component but it's seem that something is wrong when try to read variable : "reader.DataByte" in qrcode.js

Tested in : 
Desktop ( HP Envy )
Chrome Browser

Application show correctly the image from camera and when QR appear into video it did something.... but it's seem that it is not able to read "reader.DataByte"

i did the following step :

1. Just create a fresh Angular project with NG NEW qrcode
2. install component :  npm install angular2-qrscanner --save
3. Edited App.module.ts as following :

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { QrScannerModule } from 'angular2-qrscanner';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    QrScannerModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

- Edited app.component.html as following :

```
<!--The whole content below can be removed with the new code.-->
<div style="text-align:center">
  <qr-scanner [debug]="true" (onRead)="decodedOutput($event)"></qr-scanner>

</div>

```

- Edited app.component.ts as following :

```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';


decodedOutput(Evento) {

  console.log('Ho fatto qualcosa ') ;
  console.log(Evento) ;
}

}

```

**Comment by dewolft** [comment]
no one can help me with this useful component? or if there is some alternative?

**Comment by moshmage** [comment]
@dewolft the contributors are few and far, when I have some time I'll take a look - but we used this same version on prod and everything seems to be a-ok.

Which version are you using?

**Comment by dewolft** [comment]
Sure no problem dude, i've tried from the 0.1.7 to the 0.1.10 ... always the same error ( i guess ) maybe i did something wrong? it's works with computer and chrome? i just use pure Angular 2 with angluar cli

**Comment by dewolft** [comment]
this is my package.json

```
{
  "name": "dance-matik",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "angular2-datatable": "^0.6.0",
    "angular2-qrcode": "^2.0.1",
    "angular2-qrscanner": "^0.1.7",
    "angularfire2": "^4.0.0-rc0",
    "canvas": "^1.6.6",
    "core-js": "^2.4.1",
    "debug": "^3.0.1",
    "firebase": "^4.1.1",
    "jquery": "^3.2.1",
    "js-yaml": "^3.9.1",
    "minimist": "0.0.10",
    "ng2-img-tools": "^1.0.4",
    "ngx-bootstrap": "^1.7.1",
    "ngx-sharebuttons": "^3.0.0",
    "postcss-modules-extract-imports": "^1.2.0",
    "rxjs": "^5.1.0",
    "tmp": "0.0.33",
    "underscore": "^1.8.3",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.3.2",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "2.5.45",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "^2.4.2"
  }
}

```

**Comment by moshmage** [comment]
Try installing from the git repo, instead of from npm: 
```bash
npm install --save git://git@github.com:goergch/angular2-qrscanner.git
```

**Comment by dewolft** [comment]
did, same result, i tried to another laptop with fresh install of Node.js and Angular/cli, nothing change... this is new package.json :

```
{
  "name": "qr-code-test",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "angular2-qrscanner": "git+https://github.com/goergch/angular2-qrscanner.git",
    "core-js": "^2.4.1",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.3.2",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}

```

**Comment by moshmage** [comment]
So, I just issued

```bash
$ ng new qrtest
$ npm install --save git://git@github.com:goergch/angular2-qrscanner.git
```
import QrScannerModule onto app.module.ts then added to app.component.ts 
```typescript
decodedOutput($event: any) {
	console.log('the event:', $event);
  }
```
and add to app.component.html
```html
<qr-scanner
  [debug]="false"    
  [canvasWidth]="640"   
  [canvasHeight]="480"
  [mirror]="false" 
  [stopAfterScan]="true"
  [updateTime]="500"
  (onRead)="decodedOutput($event)"></qr-scanner>
```

This worked.

**Comment by dewolft** [comment]
![image](https://user-images.githubusercontent.com/28112162/29822359-79f1e022-8ccb-11e7-85cd-e4c8c95b4947.png)

This one, correction type "M" size 150

maybe is that the problem? but if i try to read this QRCode with another app it's work like a charm...
i'll try with another one

**Comment by dewolft** [comment]
![image](https://user-images.githubusercontent.com/28112162/29822855-35e5abd2-8ccd-11e7-97ad-b27dc7b13449.png)

i've used this, Correction code "M" size 150, generated with angular2-qrcode ... maybe is this the problem?
but i've tried to read it with other app and works like a charm ( i try to read it with http://webqr.com/ that is the webporting of https://github.com/LazarSoft/jsqrcode )

**Comment by moshmage** [comment]
this is what I get on the console after reading your qr-code:
`the event: 0;-KsEd4lV6zYgg5jjrZNy;-KqUH20e8BDUDxDOK4o2;BAILA OPEN`

**Comment by moshmage** [comment]
No problemo, we like happy customers :)

**Comment by dewolft** [comment]
sorry to disturb you again... component works well now... but after the second scan it stop reading QR code from camera (video is still visible) (i've set the [stopAfterScan]="false" )... there is a way to call from my component the method startScanning() ?
maybe it's a stupid question ( i'm new in using angular and typescript )

**Comment by moshmage** [comment]
@dewolft no need to, just wiggle your picture about; I had some trouble getting you picture to work (webcams quality and picture quality matter), but it did work more than once with `stopAfterScan=false`

**Comment by dewolft** [comment]
ok, i fix it just create fresh component when i need it, i've identify the QR code that the component don't read... i don't know why...

![image](https://user-images.githubusercontent.com/28112162/29899115-ca7a81ec-8de9-11e7-84bd-ec536cef815f.png)

it's generated by server side application...

**Comment by dewolft** [comment]
i found the problem. this component is not able to read QRCode encoded with UTF-8 or ASCII charset...

if anyone will have my same problem... just ENCODE your QRCODE with standard : ISO 8859-1

@moshmage : thanks for your support and patience :) maybe can be an implementation idea implement also UTF-8 support for the scanner
