### ISSUE TITLE
Ios/Android support

### ISSUE THREAD

**Issue by dewolft** [goergch/angular2-qrscanner#21]
There is a way to make it works with Ios / Android ?

**Comment by goergch** [comment]
This lib is tested positive on chrome for android. 
iOS sadly won't work. There is no known way to get the camera image inside the browser.

**Comment by MrGoro** [comment]
I just stumbeled upon this issue trying to use this library with Safari on iOS. Found out that iOS 11+ supports the [Media Capture API](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Safari_11_0/Safari_11_0.html).

Does this enable you implementation (maybe with some adjustments) to be used on iOS?
