### ISSUE TITLE
cant use with angular2

### ISSUE THREAD

**Issue by nitinsaali** [goergch/angular2-qrscanner#24]
I am using angular2. when I import modules and run ng build then ng serve getting error saying 

@angular/core/index"' has no exported member 'Renderer2'

I googled and came to know Renderer2 is in angular4.

any workaround to get this working?

Thanks In advance

**Comment by moshmage** [comment]
minimum reproduction ?

**Comment by nitinsaali** [comment]
what do you mean?

**Comment by moshmage** [comment]
I'm using this on production with AOT - your problem isn't a common one; Could you provide me with a simple plunkr reproducing your problem ?

Alternatively, could you try vNext branch and see if that does it?

**Comment by nitinsaali** [comment]
I had to switch to Angular 4 from 2, then its resolved now
