### ISSUE TITLE
[stopAfterScan]="false" only performs two scans

### ISSUE THREAD

**Issue by jdgarvey** [goergch/angular2-qrscanner#26]
If I specify `[stopAfterScan]="false"` on the component and provide the default `[updateTime]="500"`, the `onRead` callback only fires twice and then nothing happens. Nothing more is scanned.

I also tried various update times both`> 500` and `< 500` and sometimes I got one scan, sometimes two, but never more than two.

In the case of the update time being 500, I did some debugging in `qrcode.js` inside of the node module, and it looks like after the second scan, both the `process` and `decode` methods stop firing.

Perhaps this is a weird `setTimeout` issue?

Thanks!

**Comment by Zwimber** [comment]
+1

**Comment by moshmage** [comment]
You guys can circumvent this by triggering the `start` of the component manually, I'll try and write a quickfix in the meanwhile

**Comment by Zwimber** [comment]
That does indeed work. After a scan manually disabling the scanner and restarting it with the functions `startScanning()` and `stopScanning()`

**Comment by moshmage** [comment]
@Zwimber @jdgarvey check [vNext](https://github.com/goergch/angular2-qrscanner/tree/vNext) branch and yell back if it solves your pain :)

**Comment by dewolft** [comment]
+1
