### ISSUE TITLE
Error: Cannot find module '@angular-devkit/core'

### ISSUE THREAD

**Issue by abelardolg** [goergch/angular2-qrscanner#35]
Hi,

A mere few minutes ago, I downloaded this package but this error was showed.

Another question: inside the 'dist' folder, I didn't see any index.html; how should I run this project at a public server?

Best regards.

**Comment by Zwimber** [comment]
This is a problem with the current angular version, if I recall correctly it is solved by manually installing the requested package. 

```bash
npm install --save @angular-devkit
```

**Comment by abelardolg** [comment]
Is it fixed now? 

If not, let me know when you fix it. 

Thanks in advance. 

Best regards.
