### ISSUE TITLE
Event not trigger : (onRead)="decodedOutput($event)"

### ISSUE THREAD

**Issue by praveenrengarajan** [goergch/angular2-qrscanner#38]
OnRead event not triggering, 
`<qr-scanner
    [debug]="true"   
    [mirror]="true"
    (onRead)="decodedOutput($event)"></qr-scanner>`
debug,mirror and other canvas size attributes are working, but onRead not working.
In my-component.ts
`ngOnInit() {

  }
  decodedOutput($event: string) {
    alert();
    console.log('Decoded', $event);
  }`

**Comment by praveenrengarajan** [comment]
@goergch

**Comment by alefz3r0** [comment]
same here...

**Comment by praveenrengarajan** [comment]
@alefz3r0 If you couldn't solution for this like me, you can try this module https://github.com/werthdavid/ngx-zxing

**Comment by alefz3r0** [comment]
Thanks mate, that component works like a charm

**Comment by goergch** [comment]
The onRead Callback is no more triggered in version 1.0.1. See example app for details

**Comment by praveenrengarajan** [comment]
@goergch  uninstalled old version and installed new as per README, now am getting 
`TypeError: Cannot read property 'getMediaDevices' of undefined`
