### ISSUE TITLE
Not working on ios

### ISSUE THREAD

**Issue by Pikon2** [goergch/angular2-qrscanner#42]
Thanks for this library.

I am trying it from a ios 11.2 safari browser. Somehow, it is not able to open the camera. Once I allow the camera, It is showing black screen.

**Comment by frostyandy2k** [comment]
I don't get the prompt on iOS. But I am also not serving over HTTPS. In Chrome on Mac it works great.

**Comment by Pikon2** [comment]
Well I am serving over HTTPS.  Mine is working on android. But from some reason not able to open the camera on ios.

Can you share a sample code which is working on ios?

**Comment by Pikon2** [comment]
Able to make it work.

**Comment by frostyandy2k** [comment]
How did you do it? Please always post the solution.

**Comment by mayadafahim** [comment]
@Pikon2  how did you make it work

**Comment by kaharkapil** [comment]
> Thanks for this library.
> 
> I am trying it from a ios 11.2 safari browser. Somehow, it is not able to open the camera. Once I allow the camera, It is showing black screen.

Hey did you found any solution to that.

**Comment by kaharkapil** [comment]
> Able to make it work.

@Pikon2 How did you make it work?

**Comment by kaharkapil** [comment]
> @Pikon2 how did you make it work

@mayadafahim Hey did you find any solution to this?
